param([Parameter(Mandatory=$true)]$Spec)

$LogPath = "C:\CRM-Jarvis\generated\logs\javascript-generator.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message"
    Add-Content -Path $LogPath -Value "[$timestamp] [$Level] $Message"
}

Write-Host ""
Write-Host "========== JavaScript Generator ==========" -ForegroundColor Cyan
Write-Host ""

Write-Log "Generating JavaScript form scripts..."

$jsCode = @"
// Auto-generated JavaScript for D365 Form
// Generated by JARVIS

function onLoad(executionContext) {
    var formContext = executionContext.getFormContext();
    console.log("Form loaded successfully");
    
    // Add custom logic here
    initializeForm(formContext);
}

function onSave(executionContext) {
    var formContext = executionContext.getFormContext();
    console.log("Form saving");
    
    // Validate before save
    if (!validateForm(formContext)) {
        executionContext.getEventArgs().preventDefault();
        return false;
    }
    
    return true;
}

function initializeForm(formContext) {
    // Initialize form controls
    console.log("Initializing form");
    
    // Add event handlers
    var quantityControl = formContext.getControl("quantity");
    if (quantityControl) {
        quantityControl.addOnChange(onQuantityChange);
    }
    
    var priceControl = formContext.getControl("unit_price");
    if (priceControl) {
        priceControl.addOnChange(onPriceChange);
    }
}

function onQuantityChange(executionContext) {
    var formContext = executionContext.getFormContext();
    calculateLineTotal(formContext);
}

function onPriceChange(executionContext) {
    var formContext = executionContext.getFormContext();
    calculateLineTotal(formContext);
}

function calculateLineTotal(formContext) {
    var quantity = formContext.getAttribute("quantity").getValue();
    var price = formContext.getAttribute("unit_price").getValue();
    
    if (quantity != null && price != null) {
        var lineTotal = quantity * price;
        formContext.getAttribute("line_total").setValue(lineTotal);
        console.log("Line total calculated: " + lineTotal);
    }
}

function validateForm(formContext) {
    // Validation logic
    var customerLookup = formContext.getAttribute("customer").getValue();
    
    if (customerLookup == null || customerLookup.length == 0) {
        Xrm.Navigation.openAlertDialog({
            text: "Please select a customer",
            title: "Validation Error"
        });
        return false;
    }
    
    return true;
}

function notifyManager(formContext, message) {
    console.log("Notifying manager: " + message);
}

function createInvoice(formContext) {
    console.log("Creating invoice");
}
"@

$jsPath = "C:\CRM-Jarvis\generated\plugins\form-scripts.js"
$jsCode | Set-Content -Path $jsPath
Write-Log ("JavaScript saved: " + $jsPath)

Write-Host ""
Write-Host "========== JAVASCRIPT GENERATED ==========" -ForegroundColor Green
Write-Host ""
Write-Host "File: form-scripts.js" -ForegroundColor Yellow
Write-Host "Functions generated:" -ForegroundColor Yellow
Write-Host "  - onLoad" -ForegroundColor Yellow
Write-Host "  - onSave" -ForegroundColor Yellow
Write-Host "  - calculateLineTotal" -ForegroundColor Yellow
Write-Host "  - validateForm" -ForegroundColor Yellow
Write-Host ""
Write-Host ("Saved to: " + $jsPath) -ForegroundColor Cyan
Write-Host ""

return $jsPath